### ISSUE TITLE
Netlink error 

### ISSUE THREAD

**Issue by Zahtha** [Neternels/NetHunter-Ginkgo#1]
Netlink always error, when me make tool arigedonn (evil-twin) so,, AP fake  client not responding..

**Comment by Waxaranai** [comment]
@Zahtha

**Comment by Waxaranai** [comment]
@Waxaranai 💀💀💀

**Comment by cyberknight777** [comment]
@Zahtha The kernel is EOL, there won't be any insight given to this issue until another dev comes forward to maintain it.

**Comment by Zahtha** [comment]
Oke , thks sir, i hope, that problem fixed..

**Comment by Narayankarsd** [comment]
hi rtl8821au not working what to do

**Comment by cyberknight777** [comment]
@Narayankarsd Read the comment above.
